# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transaction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11transaction.proto\x12\x11proto.transaction\"2\n\x07Request\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\"2\n\x08Response\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x1e\n\x0bJoinRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\x1e\n\x0cJoinResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xd6\x01\n\x0bParticipant\x12\x42\n\x07Prepare\x12\x1a.proto.transaction.Request\x1a\x1b.proto.transaction.Response\x12\x41\n\x06\x43ommit\x12\x1a.proto.transaction.Request\x1a\x1b.proto.transaction.Response\x12@\n\x05\x41\x62ort\x12\x1a.proto.transaction.Request\x1a\x1b.proto.transaction.Response2\xa3\x01\n\x0b\x43oordinator\x12K\n\x10StartTransaction\x12\x1a.proto.transaction.Request\x1a\x1b.proto.transaction.Response\x12G\n\x04Join\x12\x1e.proto.transaction.JoinRequest\x1a\x1f.proto.transaction.JoinResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=40
  _globals['_REQUEST']._serialized_end=90
  _globals['_RESPONSE']._serialized_start=92
  _globals['_RESPONSE']._serialized_end=142
  _globals['_JOINREQUEST']._serialized_start=144
  _globals['_JOINREQUEST']._serialized_end=174
  _globals['_JOINRESPONSE']._serialized_start=176
  _globals['_JOINRESPONSE']._serialized_end=206
  _globals['_PARTICIPANT']._serialized_start=209
  _globals['_PARTICIPANT']._serialized_end=423
  _globals['_COORDINATOR']._serialized_start=426
  _globals['_COORDINATOR']._serialized_end=589
# @@protoc_insertion_point(module_scope)
